package com.cmms.maintenance.design

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.unit.LayoutDirection

/** App language state (design preview toggle). The web app uses the same EN/AR pair. */
object Lang {
    var current by mutableStateOf("ar")
    val isRtl get() = current == "ar"
    val layoutDirection get() = if (isRtl) LayoutDirection.Rtl else LayoutDirection.Ltr
    fun toggle() { current = if (current == "ar") "en" else "ar" }
}

private val STRINGS: Map<String, Pair<String, String>> = mapOf(
    "AppName" to ("Restaurant CMMS" to "نظام صيانة المطعم"),
    "MyTasks" to ("My tasks" to "مهامي"),
    "NoTasks" to ("No tasks assigned to you right now." to "لا توجد مهام محوّلة إليك حالياً."),
    "AcceptAndStart" to ("Accept & start" to "قبول وبدء العمل"),
    "AcceptAndStartHint" to ("One tap: accept the request and start working right away." to "بضغطة واحدة: تستلم الطلب وتبدأ التنفيذ مباشرة."),
    "AcceptOnly" to ("Accept only" to "قبول فقط"),
    "StartWork" to ("Start Work" to "بدء التنفيذ"),
    "StartHint" to ("Start when you are on site and begin the work." to "اضغط عند وصولك للموقع وبدء العمل."),
    "WaitForParts" to ("Wait for Parts" to "بانتظار قطع غيار"),
    "ResumeWork" to ("Resume Work" to "استئناف العمل"),
    "AddNote" to ("Add note" to "إضافة ملاحظة"),
    "NoteOptional" to ("Note (optional)" to "ملاحظة (اختياري)"),
    "ProgressNotePlaceholder" to ("What was done / what is the issue…" to "اكتب ما تم عمله أو المشكلة…"),
    "MarkComplete" to ("Mark as Completed" to "تحديد كمنجز"),
    "CompleteHint" to ("Describe the fault and what you fixed." to "اشرح العطل وما تم إصلاحه."),
    "ResolutionNotes" to ("Resolution Notes" to "ملاحظات الحل"),
    "TechnicianNotes" to ("Technician Notes" to "ملاحظات الفني"),
    "CostLabor" to ("Labor Cost" to "تكلفة العمالة"),
    "SparePartsUsed" to ("Spare Parts Used" to "قطع الغيار المستخدمة"),
    "AddPart" to ("Add Part" to "إضافة قطعة"),
    "InStock" to ("In stock" to "المتوفر بالمخزون"),
    "Quantity" to ("Quantity" to "الكمية"),
    "SearchPartPlaceholder" to ("Search by name or part number…" to "ابحث بالاسم أو رقم القطعة…"),
    "TemporaryRepair" to ("Temporary repair" to "إصلاح مؤقت"),
    "TemporaryRepairHint" to ("Not a final fix: a follow-up request for the permanent repair is created with the due date below." to "ليس حلاً نهائياً: يُنشأ طلب متابعة للإصلاح الدائم بالموعد أدناه."),
    "PermanentRepairDue" to ("Permanent repair due by" to "موعد الإصلاح الدائم"),
    "FaultType" to ("Fault type" to "نوع العطل"),
    "FaultCause" to ("Fault cause" to "سبب العطل"),
    "QuickRequest" to ("Quick maintenance request" to "طلب صيانة سريع"),
    "Quick_FindTitle" to ("Scan the QR code on the equipment with your phone camera, or search for it here." to "امسح رمز QR الموجود على الجهاز بكاميرا الهاتف، أو ابحث عن الجهاز هنا."),
    "Quick_ScanButton" to ("Scan QR code with camera" to "امسح رمز QR بالكاميرا"),
    "Quick_ScanHint" to ("Point the camera at the QR label on the equipment" to "وجّه الكاميرا نحو ملصق QR الموجود على الجهاز"),
    "Quick_FindPlaceholder" to ("Equipment name or code" to "اسم الجهاز أو رمزه"),
    "Search" to ("Search" to "بحث"),
    "Quick_MyRequests" to ("My open requests" to "طلباتي الجارية"),
    "Quick_AllMyRequests" to ("All my requests" to "كل طلباتي"),
    "Quick_MyDeptEquipment" to ("Your department's equipment" to "أجهزة قسمك"),
    "Quick_Step1" to ("What's the problem?" to "ما المشكلة؟"),
    "Quick_Step2" to ("How urgent is it?" to "ما مدى الاستعجال؟"),
    "Quick_Step3" to ("Photo of the problem (optional)" to "صورة للمشكلة (اختياري)"),
    "Quick_StepFaultType" to ("Fault type" to "نوع العطل"),
    "Quick_DescPlaceholder" to ("Tap a problem above or write it in your own words…" to "اضغط على مشكلة من فوق أو اكتبها بكلماتك…"),
    "Quick_TakePhoto" to ("Take a photo" to "التقط صورة"),
    "Quick_Send" to ("Send request" to "إرسال الطلب"),
    "Quick_Sent" to ("Your request was sent" to "تم إرسال طلبك"),
    "Quick_SentHint" to ("It will be assigned to the right technician. You can follow its status here." to "سيتم تحويله إلى الفني المختص، ويمكنك متابعة حالته من هنا."),
    "Quick_Track" to ("Track request" to "متابعة الطلب"),
    "Quick_Another" to ("Another request for this equipment" to "طلب آخر لنفس الجهاز"),
    "Quick_OpenRequestExists" to ("There is already an open request for this equipment:" to "يوجد طلب مفتوح على هذا الجهاز:"),
    "Quick_OpenRequestHint" to ("If it's the same problem, there's no need to send a new one." to "إذا كانت نفس المشكلة فلا داعي لإرسال طلب جديد."),
    "Quick_ConfirmNeeded" to ("Awaiting your confirmation" to "بانتظار تأكيدك"),
    "Quick_NoRequests" to ("No requests yet." to "لا توجد طلبات بعد."),
    "FoodSafetyImpactQuestion" to ("Does this fault affect food safety?" to "هل يؤثر العطل على سلامة الغذاء؟"),
    "FoodSafetyImpactHint" to ("Temperature out of range, contamination risk… escalated and the food-safety officer is notified." to "حرارة خارج الحد، خطر تلوث... يُرفع الطلب تلقائياً ويُبلَّغ مسؤول سلامة الغذاء."),
    "Yes" to ("Yes" to "نعم"),
    "No" to ("No" to "لا"),
    "Optional" to ("(optional)" to "(اختياري)"),
    "MyRequests" to ("My Requests" to "طلباتي"),
    "RequestDetails" to ("Request Details" to "تفاصيل الطلب"),
    "Actions" to ("Actions" to "إجراءات"),
    "Timeline" to ("Timeline" to "السجل الزمني"),
    "AddComment" to ("Add comment" to "إضافة تعليق"),
    "CommentPlaceholder" to ("Write a comment or question…" to "اكتب تعليقاً أو استفساراً…"),
    "Back" to ("Back" to "رجوع"),
    "Call" to ("Call" to "اتصال"),
    "Requester" to ("Requester" to "مقدّم الطلب"),
    "AssignedTo" to ("Assigned To" to "مسند إلى"),
    "DueAt" to ("Due" to "موعد الإنجاز"),
    "Description" to ("Description" to "الوصف"),
    "Department" to ("Department" to "القسم"),
    "Equipment" to ("Equipment" to "المعدات"),
    "Location" to ("Location" to "الموقع"),
    "CreatedAt" to ("Created At" to "تاريخ الإنشاء"),
    "AcceptedAt" to ("Accepted at" to "وقت الاستلام"),
    "StartedAt" to ("Started at" to "وقت بدء التنفيذ"),
    "CompletedAt" to ("Completed At" to "تاريخ الإنجاز"),
    "Cost" to ("Cost" to "التكلفة"),
    "TotalCost" to ("Total Cost" to "التكلفة الإجمالية"),
    "ChecklistResults" to ("Checklist Results" to "نتائج قائمة الفحص"),
    "Compliant" to ("Compliant" to "مطابق"),
    "NotCompliant" to ("Not compliant" to "غير مطابق"),
    "Attachments" to ("Attachments" to "المرفقات"),
    "Hello" to ("Hello" to "مرحبًا"),
    "Logout" to ("Log out" to "تسجيل الخروج"),
    "Save" to ("Save" to "حفظ"),
    "Cancel" to ("Cancel" to "إلغاء"),
    "CompletedAwaitingConfirmation" to ("Completed — awaiting department confirmation" to "منجز — بانتظار تأكيد القسم"),
    "OpenTask" to ("Open" to "فتح"),
    "RecentlyCompleted" to ("Recently completed" to "أُنجزت مؤخراً"),
    "Status_New" to ("New" to "جديد"),
    "Status_UnderReview" to ("Under Review" to "قيد المراجعة"),
    "Status_Assigned" to ("Assigned" to "مسند لفني"),
    "Status_Accepted" to ("Accepted by technician" to "تم الاستلام"),
    "Status_InProgress" to ("In Progress" to "قيد التنفيذ"),
    "Status_WaitingParts" to ("Waiting for Parts" to "بانتظار قطع غيار"),
    "Status_Completed" to ("Completed" to "منجز"),
    "Status_Closed" to ("Closed" to "مغلق"),
    "Status_Reopened" to ("Reopened" to "مُعاد فتحه"),
    "Status_Cancelled" to ("Cancelled" to "ملغى"),
    "Quick_UnderWarranty" to ("Under warranty" to "تحت الكفالة"),
    "Role_Technician" to ("Technician" to "فني صيانة"),
    "Role_Employee" to ("Department Employee" to "موظف قسم"),
    "DueSoon" to ("Due soon" to "قريب الاستحقاق"),
    "Overdue" to ("Overdue" to "متأخر"),
    "NotResolvedNextStep" to ("The department reported the problem is not resolved. Review the notes, then press “Accept & start” to work on it again." to "أبلغ القسم أن المشكلة لم تُحل. راجع ملاحظات الطلب ثم اضغط «قبول وبدء العمل» لمعالجتها من جديد."),
    "AreYouSure" to ("Are you sure?" to "هل أنت متأكد؟"),
    "EquipmentInfo" to ("Equipment Info" to "بيانات المعدة"),
    "Technician" to ("Technician" to "الفني"),
    "FoodSafetyImpact" to ("Food-safety impact" to "أثر على سلامة الغذاء"),
    "ChooseRole" to ("Choose a role to preview" to "اختر الدور للمعاينة"),
    "TechnicianHint" to ("Assigned tasks, accept & track" to "المهام المسندة، قبول ومتابعة"),
    "EmployeeHint" to ("QR quick request & tracking" to "طلب سريع بالـ QR ومتابعة"),
    "DesignPreview" to ("Native design preview" to "معاينة التصميم الأصلي"),
    "WebApp" to ("Open web app" to "تطبيق الويب"),
    "WebAppHint" to ("Full app in WebView" to "التطبيق الكامل عبر الويب"),
    "UserName" to ("Username" to "اسم المستخدم"),
    "Password" to ("Password" to "كلمة المرور"),
    "Login" to ("Log in" to "تسجيل الدخول"),
    "LoginTagline" to ("Manage maintenance requests, equipment and preventive plans — all in one place." to "إدارة طلبات الصيانة والمعدات والخطط الوقائية — كل ذلك في مكان واحد."),
    "InvalidLogin" to ("Invalid username or password" to "اسم المستخدم أو كلمة المرور غير صحيحة"),
    "TooManyAttempts" to ("Too many attempts. Try again in a minute." to "محاولات كثيرة. حاول مرة أخرى بعد دقيقة."),
    "SigningIn" to ("Signing in…" to "جارٍ تسجيل الدخول…"),
    "ServerUrl" to ("Server address" to "عنوان الخادم"),
    "ServerUrlHint" to ("The address of your CMMS server, e.g. http://192.168.1.214:8000" to "عنوان خادم النظام، مثال: http://192.168.1.214:8000"),
    "ServerUnreachable" to ("Cannot reach the server — check the address and network" to "تعذر الوصول إلى الخادم — تحقق من العنوان والشبكة"),
    "Loading" to ("Loading…" to "جارٍ التحميل…"),
    "Retry" to ("Retry" to "إعادة المحاولة"),
    "CantLoadTasks" to ("Couldn't load your tasks — check the connection and retry." to "تعذر تحميل المهام — تحقق من الاتصال وأعد المحاولة."),
    "CantLoadRequests" to ("Couldn't load your requests — check the connection and retry." to "تعذر تحميل الطلبات — تحقق من الاتصال وأعد المحاولة."),
    "MarkAllRead" to ("Mark all as read" to "تعليم الكل كمقروء"),
    "NotifChannelName" to ("Maintenance notifications" to "إشعارات الصيانة"),
    "SyncChannelName" to ("Background connection" to "اتصال الخلفية"),
    "SyncNotification" to ("Connected — receiving notifications" to "متصل — يتم استقبال الإشعارات"),
    "NewNotifications" to ("You have {n} new notifications" to "لديك {n} إشعارات جديدة"),
)

fun s(key: String): String {
    val pair = STRINGS[key] ?: return key
    return if (Lang.isRtl) pair.second else pair.first
}

val LayoutDir: LayoutDirection
    @Composable get() = Lang.layoutDirection
