plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cmms.maintenance'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cmms.maintenance'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
}

dependencies {
    implementation project(':design')
}
